### ISSUE TITLE
LVM operator configuration does not create volume groups.

### ISSUE THREAD

**Issue by sbudhira** [red-hat-storage/lvm-operator#268] opened 2022-09-28 17:21 UTC
Installed SNO using Assisted-Installer on Bare Metal with two disks (1 TB each)
Installed ODF LVM operator
Configured using vg2. 
-  Storage class was created 
-  vg2 was not created ( output is attached)
-  topolvm_node pod is not running.

Attached Logs and Screenshots:
----------------
[topolvm-node-8x8q7-file-checker.log](https://github.com/red-hat-storage/lvm-operator/files/9667451/topolvm-node-8x8q7-file-checker.log)
[vg-manager-896xc-vg-manager.log](https://github.com/red-hat-storage/lvm-operator/files/9667452/vg-manager-896xc-vg-manager.log)
![Screenshot 2022-09-28 122938](https://user-images.githubusercontent.com/22056068/192847852-3457503f-49da-46ee-983e-f48d7edf5409.png)
![Screenshot 2022-09-28 122324](https://user-images.githubusercontent.com/22056068/192847853-57e34cbf-2f6e-486f-98b1-389e806fdd18.png)
[topolvm-controller-57d5786b76-hbf9z-topolvm-controller.log](https://github.com/red-hat-storage/lvm-operator/files/9667453/topolvm-controller-57d5786b76-hbf9z-topolvm-controller.log)
[controller-manager-744c976db4-bpqzn-kube-rbac-proxy.log](https://github.com/red-hat-storage/lvm-operator/files/9667454/controller-manager-744c976db4-bpqzn-kube-rbac-proxy.log)

**Comment by nbalacha** [comment] 2022-09-29 06:34
The lsblk output shows no free disks that LVMO can use because of which it cannot create any VGs. Please ensure that at least one disk is free and try again.

**Comment by nbalacha** [comment] 2022-09-30 04:38
> There are vg1 volume groups are created during installation. Can I delete these vg1? I installed SNO multiple times using ISO file and it creates these vg1 automatically every time. Should it be getting created at this time?
> 
> 1. Should these vg1 be created after installation? if no, how can I stop it from getting created these vg1 next time?
> 2. Can I delete these vg1 groups?

Please check with the SNO team about that. This is unrelated to LVMO.

**Comment by nbalacha** [comment] 2022-09-30 04:38
I'm closing this issue as this is expected behaviour for LVMO. Please reopen if you are still unable to create the vgs even after having a clean disk.

**Closed by nbalacha** 2022-09-30 04:38 UTC
